openapi: 3.0.0
info:
  title: MyTSA Tech Challenge API
  description: This is a MyTSA API interface design / specification
  license:
    name: MyTSA Tech Challenge API
  version: 0.0.1
servers:
- url: https://localhost:8080/
paths:
  /record/status:
    get:
      tags:
      - get status data
      summary: Gets all the status data
      operationId: get_status
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecordStatus'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "405":
          description: Method Not Allowed
        "415":
          description: Unsupported Media Type / Unspecified Content Type
        "500":
          description: Internal Server Error
        "504":
          description: Gateway timeout
      x-openapi-router-controller: swagger_server.controllers.get_record_status_data_controller
components:
  schemas:
    RecordStatus:
      type: array
      items:
        $ref: '#/components/schemas/StatusModel'
    StatusModel:
      type: object
      properties:
        status:
          type: string
          example: "yes"
      example:
        status: "yes"

