openapi: 3.0.0
info:
  title: Scaffoled Microservice
  description: Scaffoled Microservice design / specification
  license:
    name: Scaffoled Microservice API
  version: 0.0.1
servers:
- url: https://localhost:8080/
- url: https://localhost:8080/
paths:
  /record/status:
    get:
      tags:
      - getStatus
      summary: Gets the status
      operationId: get_status
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/record'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "405":
          description: Method Not Allowed
        "415":
          description: Unsupported Media Type / Unspecified Content Type
        "500":
          description: Internal Server Error
        "504":
          description: Gateway timeout
      x-openapi-router-controller: swagger_server.controllers.get_records_status_controller
components:
  schemas:
    record:
      type: array
      items:
        $ref: '#/components/schemas/recordModel'
    recordModel:
      type: object
      properties:
        status:
          type: string
          example: Huntsville International
      example:
        status: true

